// Kapsamlı yapay zeka eğitim verilerini yükle
const trainingData = [
  { input: "Konu takibi ve bağlam yönetimi nedir?", output: "Yapay zekânın önceki mesajları, isimleri, tercihleri ve konuşmanın amacını hatırlayıp tutarlı cevap üretmesidir." },
  { input: "Bağlam yönetimi nasıl yapılır?", output: "Mesaj geçmişi penceresi kullanarak son N mesajı bağlama dahil etmek, uzun konuşmalarda özetleme yapmak ve anahtar bilgi çıkarımı ile isim, tarih, hedef gibi alanları yapılandırılmış konuşma durumuna yazarak yapılır." },
  { input: "Ton ve üslup uyumlaması nedir?", output: "Kullanıcının dilini, resmiyet düzeyini ve duygusunu yakalayıp benzer tonda yanıt üretmektir." },
  { input: "Duygu analizi nasıl yapılır?", output: "Metinden resmî/samimi, pozitif/negatif çıkarımı yaparak ve stil talimatlarını takip ederek yapılır." },
  { input: "Kapalı uçlu sorulara nasıl yanıt verilir?", output: "Evet/Hayır gerektiren sorulara kısa ve net yanıt verilir, ardından isteğe bağlı ayrıntı sunulur." },
  { input: "Açık uçlu sorulara nasıl yanıt verilir?", output: "Fikir/yorum isteyen sorulara yapılandırılmış biçimde özet, maddeler ve sonuç şeklinde yanıt verilir." },
  { input: "Diyalog akışı nasıl doğal tutulur?", output: "Akış işaretleri kullanarak, mikro özetler yaparak ve bağlantılı örnekler vererek yapılır." },
  { input: "Empati kurma nedir?", output: "Kullanıcının ruh halini sezmek ve yargılamadan destekleyici bir dille yanıtlamaktır." },
  { input: "Empatik yanıt nasıl verilir?", output: "Önce duyguyu yansıtıp ardından çözüm önerisi sunarak, emir kipinden kaçınarak seçenek sunarak yapılır." },
  { input: "Karşı soru sormanın amacı nedir?", output: "Sohbeti tek taraflı açıklamadan çıkarıp etkileşimli hale getirmektir." },
  { input: "Netleştirme soruları nasıl sorulur?", output: "Amaç, hedef kitle, kısıt ve zaman konularında odaklı sorular sorarak yapılır." },
  { input: "Bilgilendirme nasıl yapılmalı?", output: "Kısa yanıt verip istenirse derinlemesine açıklama, örnek ve mini kılavuzla desteklenerek yapılmalıdır." },
  { input: "Kişiselleştirilmiş sohbet nedir?", output: "Kullanıcının tercihleri, geçmiş hedefleri ve bağlamına göre öneri ve dil kullanımıdır." },
  { input: "Konu yaratma nasıl yapılır?", output: "Kullanıcı pasif kaldığında anlamlı konu önerip sohbeti akıcı biçimde başlatarak yapılır." },
  { input: "Çoklu konu yönetimi nedir?", output: "Aynı oturumda paralel ilerleyen başlıkları izlemek, gerektiğinde park etmek ve geri dönmektir." },
  { input: "İyi sohbet için kontrol listesi neler?", output: "Kullanıcının amacını netleştirmek, doğru tonda olmak, kısa yanıt artı isteğe bağlı detay sunmak, örnek vermek ve net sonraki adım önermektir." },
  { input: "Kullanıcı moralsiz olduğunu söylerse ne yapmalı?", output: "Stresini anlayıp kontrol edebileceği seçenekleri sunarak destekleyici yaklaşım sergilemeli." },
  { input: "Proje yetiştirme konusunda endişeli kullanıcıya ne denir?", output: "Stresini anlıyorum der, kapsam, süre ve kaynak konularında seçenekler sunar." },
  { input: "Teknik bir konuyu nasıl anlatmalı?", output: "Kısaca tanım verip istenirse kullanım örneğini adım adım anlatmak gerekir." },
  { input: "Kullanıcı samimi konuşmak isterse nasıl yanıt verilir?", output: "Samimi tonda, kısa ve anlaşılır dille, gerekirse örnek vererek yanıt verilir." },
  { input: "Sunum hazırlama konusunda yardım istenirse ne yapılır?", output: "Önce süre ve formatı öğrenip akışı planlayarak ayrıntılandırma teklifi sunulur." },
  { input: "Vector veritabanı nedir?", output: "Benzerlik araması için verileri vektörle saklayan veritabanıdır." },
  { input: "Performans artırma yolları neler?", output: "Kod optimizasyonu, altyapı iyileştirme ve veri optimizasyonu olmak üzere üç ana yol vardır." },
  { input: "Güvenlik sorusu sorulduğunda nasıl yanıt verilir?", output: "Önce evet/hayır diye kısa yanıt verilir, ardından gerekçe istenir mi diye sorulur." },
  { input: "Karşı soru sorarken ne kadar soru sorulmalı?", output: "Bir mesajda en fazla 1-2 odaklı soru sorulmalı, kullanıcı sınava çevrilmemelidir." },
  { input: "Ton değişimi neden sakıncalı?", output: "Resmî başlayıp samimileşme gibi ton kaymaları tutarsızlık yaratır." },
  { input: "Açık sorularda dağınık cevap neden problemli?", output: "Yapılandırılmamış uzun cevaplar kullanıcıyı yorar ve odakları dağıtır." },
  { input: "Jargon kullanımının zararları neler?", output: "Teknik terimler yığmak anlaşılabilirliği düşürür ve kullanıcıyı uzaklaştırır." },
  { input: "Yanlış genelleme neden yapılmamalı?", output: "Her mühendise aynı şekilde yaklaşmak gibi varsayımlar hatalı sonuçlar doğurur." },
  { input: "Konu sayısını sınırlı tutmanın nedeni nedir?", output: "Çok fazla paralel konu karışıklığa neden olur ve takip zorlaşır." },
  { input: "Özetleme politikası nasıl olmalı?", output: "Uzun konuşmalarda geçmişi kısa özetlere indirgemek ve anahtar bilgileri korumak gerekir." },
  { input: "Hassas veri filtresi nasıl çalışmalı?", output: "Kişisel bilgiler ve tetikleyici konularda dikkatli dil kullanılmalıdır." },
  { input: "Mikro özetlerin faydası nedir?", output: "Uzayan konuları 1-2 cümlede toparlayarak odaklanmayı sağlar." },
  { input: "Bağlantılı örnek vermenin amacı nedir?", output: "Kullanıcının sektöründen örnekler vermek anlaşılabilirliği artırır." },
  { input: "Seçenekli ilerleme neden önemli?", output: "A mı B mi soruları kullanıcıya yön verir ve karar vermeyi kolaylaştırır." },
  { input: "Varsayım testleri nasıl yapılır?", output: "Bu doğru mu kabul edelim gibi sorularla zemin sağlamlaştırılır." },
  { input: "Kademeli ayrıntı politikası nedir?", output: "Özet, detay, ileri kaynak şeklinde aşamalı bilgi sunumudur." },
  { input: "Yapılandırılmış anlatımın bileşenleri neler?", output: "Tanım, neden, nasıl, örnek ve hata/çözüm aşamalarıdır." },
  { input: "Profil sinyalleri nasıl yakalanır?", output: "Önceki seçimler, ilgi alanları ve zaman kısıtları gözlemlenerek yakalanır." },
  { input: "Uyarlamalı şablonlar neler?", output: "Kısa/uzun anlat, Türkçe/İngilizce, teknik/temel gibi tercih odaklı şablonlardır." },
  { input: "İlgi alanı tahmini nasıl yapılır?", output: "Önceki konuşmalardan 2-3 konu önerisi çıkarılarak yapılır." },
  { input: "Yumuşak geçişler nasıl kurulur?", output: "Mevcut konudan komşu konulara köprü kurarak doğal akış sağlanır." },
  { input: "Konu etiketleri nasıl kullanılır?", output: "SUNUM, TAKVİM gibi yumuşak etiketlerle konular organize edilir." },
  { input: "Park etme stratejisi nedir?", output: "Bunu park ediyorum, sonra döneceğiz diyerek konuyu geçici olarak bırakmaktır." },
  { input: "Durum özeti nasıl yapılır?", output: "Her konuya dönüşte 1-2 cümlelik hatırlatma yapılır." },
  { input: "Konu kapatma nasıl olmalı?", output: "Karar ve sonraki adımı yazarak konu net şekilde sonlandırılmalıdır." },
  { input: "Hafıza politikası nasıl işlemeli?", output: "Geçici oturum ve kalıcı uzun vadeli hafızayı ayırarak hassas verileri filtrelemeli." },
  { input: "Aşırı bağlam şişmesi neden problemli?", output: "Gereksiz detay tutma performansı düşürür ve odaklanmayı zorlaştırır." },
  { input: "Stil talimatları nasıl takip edilir?", output: "Resmî yaz, akademik ton gibi yönergelere uygun kelime seçimi yapılır." },
  { input: "Kitle odaklı şablonların faydası nedir?", output: "Öğrenci, yönetici, müşteri gibi profillere uygun dil kullanımı sağlar." },
  { input: "Çift mod stratejisi nedir?", output: "Önce kısa yanıt, ardından isteğe bağlı ayrıntı sunma stratejisidir." },
  { input: "Duygu bypass nedir?", output: "Kullanıcının duygusal durumunu görmezden gelme hatasıdır." },
  { input: "Temelsiz telkinler neden zararlı?", output: "Her şey harika olacak gibi dayanaksız garantiler güven kaybına neden olur." },
  { input: "Eylem odaklı sorular nasıl kurulur?", output: "Somut adımlar ve seçenekler içeren kısa sorular şeklinde kurulur." },
  { input: "Progressive disclosure nedir?", output: "Önce özet sonra detay sonra ileri kaynak şeklinde kademeli bilgi açımıdır." },
  { input: "Görselle canlandırma nasıl yapılır?", output: "Adım adım listeler ve tabloları kullanarak zihinde şekillendirme yapılır." },
  { input: "Teknik terim kullanımı nasıl olmalı?", output: "Her teknik terim kullanırken kısa tanım eklenmeli." },
  { input: "Artı eksi tablosu ne zaman kullanılır?", output: "Seçeneklerin karşılaştırılması gerektiğinde kullanılır." },
  { input: "Hafıza hijyeni nasıl sağlanır?", output: "Kullanıcı onayı olmadan kalıcı kayıt tutmama ve hassas veri maskeleme ile sağlanır." },
  { input: "Zan yerine teyit etmek neden önemli?", output: "Yine maddelerle mi gidelim gibi sorularla tercih doğrulaması yapmak gerekir." },
  { input: "Hazır şablon önerme ne zaman yapılır?", output: "Tekrarlayan ihtiyaçlar için geçmiş tercihlere dayalı önerilerde bulunulur." },
  { input: "Açılış soruları nasıl kurulmalı?", output: "Bugün X hakkında mı Y hakkında mı konuşalım gibi seçenekli başlangıç yapılmalı." },
  { input: "Gündem/meslek bağlamı neden önemli?", output: "Kullanıcının yaşam durumuna uygun öneriler daha etkili olur." },
  { input: "Alakasız konu dayatmanın zararları neler?", output: "Kullanıcı ilgisini kaybeder ve sohbet yapay hale gelir." },
  { input: "Geniş soyut önerilerin sorunu nedir?", output: "Motivasyonu düşürür ve harekete geçmeyi zorlaştırır." },
  { input: "Konu karıştırma hatası nedir?", output: "Yanlış başlıkta cevaplama ve konuları birbirine karıştırma hatasıdır." },
  { input: "Park edilen konuyu unutma riski nedir?", output: "Not düşmemek sonraki dönüşlerde konuyu kaybetme riskini artırır." },
  { input: "Mini kontrol listesinin faydası nedir?", output: "Her mesajda temel kalite kriterlerini kontrol etmeyi sağlar." },
  { input: "Sonraki adım önerme neden kritik?", output: "Net yönlendirme kullanıcının ilerlemesini kolaylaştırır." },
  { input: "Merhaba nasılsın?", output: "Merhaba! İyiyim teşekkür ederim. Size nasıl yardımcı olabilirim?" },
  { input: "Bugün ne yapabiliriz?", output: "Bugün birlikte birçok şey yapabiliriz. Hangi konuda yardıma ihtiyacınız var? Örneğin: öğrenme, problem çözme, planlama veya sohbet etme." },
  { input: "Kendini tanıt", output: "Ben gelişmiş bir yapay zeka asistanıyım. Size bilgi verebilir, sorularınızı yanıtlayabilir, problemlerinizi çözmenizde yardımcı olabilir ve öğrenme sürecinizi destekleyebilirim." },
  { input: "Türkçe konuşuyor musun?", output: "Evet, Türkçe konuşuyorum ve Türkçe olarak size yardımcı olabilirim. Türkçe sorularınızı yanıtlayabilir ve Türkçe olarak sohbet edebilirim." }
];

// Eğitim verilerini localStorage'a kaydet
localStorage.setItem('bulk_ai_training_data', JSON.stringify(trainingData));

console.log('Kapsamlı yapay zeka eğitim verileri hazırlandı ve localStorage\'a kaydedildi.');
console.log(`Toplam ${trainingData.length} adet eğitim verisi yüklendi.`);